/* SPDX-License-Identifier: GPL-2.0-or-later */
#include <assert.h>
#include <string.h>
#include "cdj_c674x_loop.h"
static bool even_tag(void *opaque, uint32_t tag)
{
    (void)opaque;
    return !(tag & 1);
}
/* METAMORPHIC, deliberately. This is a second implementation of the same
 * dispatch rule, not an external oracle: every absolute value below is
 * generated by the test itself, so a shared misreading would pass. What it
 * pins is an equivalence SPRUFE8B states. 7.7.3 and 7.7.3.4 (printed pages
 * 678-679) index the loop buffer by LBC, which "is incremented by 1" each
 * cycle and reset to 0 at every stage boundary, and dispatch "instructions
 * marked as valid in the loop buffer at the current LBC"; 7.7.1 (printed page
 * 677) and 7.7.3.5 (printed page 679) fix the order as the order they were
 * loaded in. So: scanning every origin linearly and keeping the ones whose
 * age is a multiple of ii must give exactly the same operations, in the same
 * order, as striding the origins by ii from cycle % ii - which is what
 * cdj_c674x_loop_issue_filtered does for speed. The reference below is the
 * linear form; the production one is the strided form. Divergence means the
 * stride optimisation, the mask filter or the iteration cut-off is wrong. */
static bool reference_issue(CdjC674xLoop *loop, uint32_t tags[8], unsigned *count,
                                  bool *post_fetch, bool *drained,
                                  bool (*allow)(void *, uint32_t), void *opaque)
{
    uint32_t result[8];
    unsigned n = 0;
    if (!loop->ii || (!loop->sealed && loop->cycle >= 48)) return false;
    for (unsigned origin = 0; origin < loop->length; ++origin) {
        if (origin > loop->cycle) continue;
        uint64_t age = loop->cycle - origin;
        /* Predicate loops are normally unbounded.  Interrupt detection turns
         * their current launch count into a finite epilog schedule, just as
         * it does for SPLOOP/SPLOOPD (SPRUFE8B 7.13.1). */
        bool interrupt_epilog = loop->predicate_loop && loop->sealed &&
                                loop->end_cycle != UINT64_MAX;
        if (age % loop->ii ||
            ((!loop->predicate_loop || interrupt_epilog) &&
             age / loop->ii >= loop->iterations))
            continue;
        for (unsigned j = 0; j < loop->count[origin]; ++j) {
            uint32_t tag = loop->tags[origin][j];
            if (allow && !allow(opaque, tag)) continue;
            if (n == 8) return false;
            result[n++] = tag;
        }
    }
    if (n) memcpy(tags, result, n * sizeof(*tags));
    *count = n;
    *post_fetch = loop->sealed && loop->cycle >= loop->post_cycle;
    *drained = loop->sealed && loop->cycle >= loop->end_cycle;
    ++loop->cycle;
    return true;
}

static void compare_schedulers(void)
{
    const uint64_t cycles[] = {0,1,2,7,15,16,31,47,48,63,96,127,UINT64_MAX-1};
    for (unsigned ii = 1; ii <= 16; ++ii)
    for (unsigned length = 0; length <= 48; ++length)
    for (unsigned mode = 0; mode < 4; ++mode)
    for (unsigned iteration = 0; iteration < 4; ++iteration)
    for (unsigned t = 0; t < sizeof(cycles)/sizeof(cycles[0]); ++t)
    for (unsigned filter = 0; filter < 2; ++filter) {
        CdjC674xLoop a;
        assert(cdj_c674x_loop_init(&a, ii, iteration == 3 ? UINT32_MAX : iteration));
        a.length = length; a.cycle = cycles[t];
        a.sealed = mode != 0; a.predicate_loop = mode >= 2;
        a.post_cycle = 63; a.end_cycle = mode == 2 ? UINT64_MAX : 96;
        for (unsigned origin = 0; origin < length; ++origin) {
            a.count[origin] = origin % 4;
            for (unsigned j = 0; j < a.count[origin]; ++j)
                a.tags[origin][j] = origin * 8 + j;
        }
        CdjC674xLoop b = a;
        uint32_t ta[8] = {0}, tb[8] = {0};
        unsigned na = 99, nb = 99;
        bool pa = false, pb = false, da = false, db = false;
        bool (*allow)(void *, uint32_t) = filter ? even_tag : NULL;
        bool ra = reference_issue(&a, ta, &na, &pa, &da, allow, NULL);
        bool rb = cdj_c674x_loop_issue_filtered(&b, tb, &nb, &pb, &db, allow, NULL);
        assert(ra == rb && na == nb && pa == pb && da == db);
        assert(!memcmp(ta, tb, sizeof(ta)) && !memcmp(&a, &b, sizeof(a)));
    }
}

static void test_immediate_reload_trace(void)
{
    /* TI Example 7-15's seven-cycle source: LDW, NOP 4, MV, STW.
     * Ghidra's independent C6000ImmediateReloadTest records the old STW
     * alongside the new MV at cycle 12 and the final STW at cycle 19. */
    CdjC674xLoop loop;
    assert(cdj_c674x_loop_init(&loop, 1, 7));
    loop.length = 7; loop.sealed = true;
    loop.count[0] = loop.count[5] = loop.count[6] = 1;
    loop.tags[0][0] = 1; loop.tags[5][0] = 2; loop.tags[6][0] = 4;
    loop.post_cycle = UINT64_MAX; loop.end_cycle = 13;
    uint64_t start = 0, old_start = 0, old_end = 0, post_end = 0;
    for (unsigned t = 0; t < 20; ++t) {
        uint32_t tags[8] = {0};
        unsigned count = 0;
        bool post = false, drained = false;
        assert(cdj_c674x_loop_issue_reload(&loop, start, old_start,
                                           old_end, post_end, tags, &count,
                                           &post, &drained, NULL, NULL));
        assert(post == (t >= 7));
        if (t == 12) assert(count == 3 && tags[0] == 4 && tags[1] == 1 &&
                             tags[2] == 2);
        if (t == 13) assert(count == 3 && tags[0] == 1 && tags[1] == 2 &&
                             tags[2] == 4);
        if (t == 19) assert(count == 1 && tags[0] == 4 && drained);
        if (t == 6) {
            old_start = 0; old_end = 13; start = 7;
            loop.end_cycle = 20; loop.post_cycle = 7; post_end = 14;
        }
        if (t == 13) { loop.post_cycle = 14; post_end = 21; }
    }
}

int main(void)
{
    compare_schedulers();
    test_immediate_reload_trace();
    CdjC674xLoop loop;
    uint32_t out[8], tag;
    unsigned n;
    bool post, drained;
    /* SPRUFE8B Table 7-1: eight iterations, II=1, LDW/NOP4/MV/STW.
     * Each bit marks a functional operation issued during that cycle. */
    const unsigned expected[] = {1,1,1,1,1,3,7,7,6,6,6,6,6,4};
    assert(cdj_c674x_loop_init(&loop, 1, 8));
    for (unsigned t = 0; t < 14; ++t) {
        if (t <= 6) {
            tag = t == 0 ? 1 : t == 5 ? 2 : t == 6 ? 4 : 0;
            assert(cdj_c674x_loop_load(&loop, &tag, tag ? 1 : 0, t == 6, 6));
        }
        assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
        unsigned mask = 0;
        for (unsigned j = 0; j < n; ++j) mask |= out[j];
        assert(mask == expected[t] && !post && !drained);
    }
    assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
    assert(n == 0 && post && drained);

    /* Functional run-ahead is opt-in and affects only delayed-count loops.
     * It buys two epilog cycles without weakening the strict default. The
     * value 10 = iterations * ii + delay + 2 has NO manual referent: the +2 is
     * this repository's bounded development approximation, documented at
     * cdj_c674x_loop.c's post_cycle comment, and the assertion pins our own
     * choice so it cannot drift, not an architectural claim. */
    cdj_c674x_loop_set_functional_timing(true);
    assert(cdj_c674x_loop_functional_timing());
    assert(cdj_c674x_loop_init(&loop, 1, 8));
    loop.delayed_count = true;
    for (unsigned t = 0; t < 7; ++t) {
        tag = t == 0 ? 1 : 0;
        assert(cdj_c674x_loop_load(&loop, &tag, tag ? 1 : 0, t == 6, 0));
        assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
    }
    assert(loop.post_cycle == 10);
    cdj_c674x_loop_set_functional_timing(false);
    assert(!cdj_c674x_loop_functional_timing());

    /* II=2: post-loop instructions may overlap the draining stores.
     *
     * HONEST PROVENANCE, because the audit (DSP_ARCHITECTURE_COVERAGE.md §7)
     * named this case as circular and that finding still stands. The derivation
     * below is sound and was written against the manual, but it was written
     * AFTER these expected values already matched the implementation - the
     * numbers are unchanged from before it existed. A derivation produced in
     * that order cannot distinguish "the manual implies this" from "the
     * implementation produced this and the manual does not contradict it". Treat
     * this as a consistency check with a documented rationale, not as an
     * independent reference-backed assertion. Making it genuinely independent
     * means deriving the cycle numbers from §7.7.3 before running anything, or
     * getting them from a TI oracle. Body: one operation at
     * loading cycle 0 (tag 1) and one at loading cycle 5 (tag 2), dynlen 6,
     * ii 2, ILC 3. By 7.7.3 / 7.7.3.4 (printed pages 678-679) an operation
     * loaded at offset n issues on every cycle congruent to n modulo ii, once
     * per iteration, so tag 1 issues at cycles 0, 2, 4 and tag 2 at 5, 7, 9.
     * By 7.9.4 (printed page 686) program memory fetch resumes when the
     * draining counter reaches delay = fstg * ii + fcyc = 0, and 7.7.3.5
     * (printed page 679) starts that counter on the cycle after the
     * termination condition is true, i.e. after the third iteration has been
     * launched: cycle 3 * 2 = 6. By 7.7.3.2 (printed page 678) the loop is
     * idle once it "is finished draining", one cycle after tag 2's last issue
     * at cycle 9, so cycle 10. */
    assert(cdj_c674x_loop_init(&loop, 2, 3));
    for (unsigned t = 0; t <= 10; ++t) {
        if (t <= 5) {
            tag = t == 0 ? 1 : t == 5 ? 2 : 0;
            assert(cdj_c674x_loop_load(&loop, &tag, tag ? 1 : 0, t == 5, 0));
        }
        assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
        unsigned expected_tag = (t <= 4 && !(t & 1)) ? 1 :
                                (t >= 5 && t <= 9 && (t & 1)) ? 2 : 0;
        assert(n == (expected_tag ? 1u : 0u));
        if (n) assert(out[0] == expected_tag);
        assert(post == (t >= 6) && drained == (t >= 10));
    }

    /* Zero iterations still load the body but issue none of its operations. */
    assert(cdj_c674x_loop_init(&loop, 2, 0));
    for (unsigned t = 0; t <= 4; ++t) {
        tag = 1;
        if (t < 3) assert(cdj_c674x_loop_load(&loop, &tag, 1, t == 2, 0));
        assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
        assert(!n && post == (t == 4) && drained == (t == 4));
    }
    assert(!cdj_c674x_loop_init(&loop, 0, 1));
    assert(cdj_c674x_loop_init(&loop, 16, 1));
    assert(!cdj_c674x_loop_init(&loop, 17, 1));
    assert(cdj_c674x_loop_init(&loop, 1, 2));
    uint32_t full[8] = {1,2,3,4,5,6,7,8};
    assert(cdj_c674x_loop_load(&loop, full, 8, false, 0));
    assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
    assert(cdj_c674x_loop_load(&loop, full, 8, true, 0));
    CdjC674xLoop before = loop;
    assert(!cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
    assert(!memcmp(&loop, &before, sizeof(loop)));
    /* Masks apply before capacity validation: 16 candidates, eight issued. */
    assert(cdj_c674x_loop_issue_filtered(&loop, out, &n, &post, &drained, even_tag, NULL));
    assert(n == 8);
    for (unsigned j = 0; j < n; ++j) assert(out[j] == 2 * (j % 4 + 1));
    /* A predicate loop has no finite iteration count or count-driven epilog. */
    assert(cdj_c674x_loop_init(&loop, 2, 0));
    loop.predicate_loop = true;
    tag = 99;
    assert(cdj_c674x_loop_load(&loop, &tag, 1, true, 0));
    for (unsigned t = 0; t < 100; ++t) {
        assert(cdj_c674x_loop_issue(&loop, out, &n, &post, &drained));
        assert(n == (t % 2 ? 0u : 1u) && !post && !drained);
        if (n) assert(out[0] == 99);
    }
    return 0;
}
