/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef CDJ_C6747_TIMER_H
#define CDJ_C6747_TIMER_H

#include <stdbool.h>
#include <stdint.h>

#define CDJ_C6747_TIMER_COUNT 2u
#define CDJ_C6747_TIMER0_BASE 0x01c20000u
#define CDJ_C6747_TIMER1_BASE 0x01c21000u

/* SPRUH91D chapter 28 register state. Internal/external clock progression,
 * output pins, watchdog reset, DMA events and INTC delivery are deliberately
 * outside this register-level batch. */
typedef struct {
    uint32_t emumgt, gpintgpen, gpdatgpdir;
    uint32_t tim12, tim34, tim34_shadow;
    uint32_t prd12, prd34, tcr, tgcr, wdtcr;
    uint32_t rel12, rel34, cap12, cap34, intctlstat;
    uint32_t compare[8];
    uint8_t tim34_shadow_valid;
} CdjC6747Timer;

/* Which half of one Timer64P a rate query is about. */
#define CDJ_C6747_TIMER_HALF_12 0u
#define CDJ_C6747_TIMER_HALF_34 1u

/* The input clock of one half of one Timer64P, as an exact unreduced
 * fraction: *numerator Hz over *denominator, given AUXCLK in Hz from
 * cdj_c6747_pll_auxclk_hz().  AUXCLK is the timer's internal clock source:
 * SPRUH91D Table 6-2 printed page 104 (PDF page 104) and Table 7-1 printed
 * page 118 put "Timers" on AUXCLK, and 28.1.5.2.1 printed page 1229 says
 * the internal clock source "is generated by the PLL controller".  The PSC
 * does not appear in this path at all: Tables 8-1 and 8-2 printed pages 140
 * and 141 assign no LPSC to either Timer64P, and 8.2 printed page 140 says
 * such modules "do not have their module reset/clocks controlled by the PSC
 * module".
 * False wherever the manuals fix no rate; the outputs are then untouched.
 * This is a rate, not a run/stop condition: TGCR's TIMnRS resets, TCR's
 * ENAMODEn and TCR's TIEN12 external gate (printed pages 1253 and 1254) all
 * decide whether the counter advances, and none of them change this rate.
 * Nothing in this file counts - deliberately. */
bool cdj_c6747_timer_input_hz(const CdjC6747Timer *s, uint32_t auxclk_hz,
                              unsigned half, uint64_t *numerator,
                              uint32_t *denominator);

void cdj_c6747_timers_reset(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT]);
bool cdj_c6747_timers_read(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT],
                           uint32_t address, uint32_t *value);
/* Check phase is side-effect free. Reserved offsets, writes to REVID and
 * non-word accesses remain unmapped so validation runs fail closed. */
bool cdj_c6747_timers_write(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT],
                            uint32_t address, uint64_t value, unsigned size,
                            bool commit);

#endif
