/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef CDJ_C6747_TIMER_H
#define CDJ_C6747_TIMER_H

#include <stdbool.h>
#include <stdint.h>

#define CDJ_C6747_TIMER_COUNT 2u
#define CDJ_C6747_TIMER0_BASE 0x01c20000u
#define CDJ_C6747_TIMER1_BASE 0x01c21000u

/* SPRUH91D chapter 28 register state plus the GP counters.  The prescale
 * counters need no field of their own: in dual 32-bit unchained mode the
 * architectural prescale count IS TGCR's TDDR34 (Table 28-18, printed page
 * 1254) and in chained mode it IS TIM34 (28.1.5.4.2.1, printed page 1232).
 * CAP12/CAP34 DO have an internal writer: Read Reset Mode (28.1.5.4.2.2.6,
 * printed page 1238) captures the counter into them on a read of TIM12/TIM34
 * when PLUSEN, 32-bit unchained mode and the half's READRSTMODEn are set, and
 * reloads PRDn from RELn when ENAMODEn = 3h.  That is implemented here.  What
 * is absent is EXTERNAL-event capture, so INTCTLSTAT's EVTINTSTATn never sets.
 *
 * Still deliberately outside this model, each a cost judgement rather than an
 * absence of firmware-visible effect:
 *  - Output pins TM64P_OUT12/34 and with them TCR's TSTAT12/PWID12/CP12 pulse
 *    generator.  TSTAT12 is a readable TCR bit, so firmware polling it as a
 *    period-elapsed flag would spin forever; Table 28-17 (printed pages
 *    1252-1253) fully specifies when it asserts and for how long from CP12 and
 *    PWID12, needing no board fact - only a pulse countdown this patch chose
 *    not to add.
 *  - The watchdog's device-level reset, which no board here can drive.
 *  - DMA events (TEVTn); only the INTC route is wired. */
typedef struct {
    uint32_t emumgt, gpintgpen, gpdatgpdir;
    uint32_t tim12, tim34, tim34_shadow;
    uint32_t prd12, prd34, tcr, tgcr, wdtcr;
    uint32_t rel12, rel34, cap12, cap34, intctlstat;
    uint32_t compare[8];
    uint8_t tim34_shadow_valid;
} CdjC6747Timer;

/* Which half of one Timer64P a rate query is about. */
#define CDJ_C6747_TIMER_HALF_12 0u
#define CDJ_C6747_TIMER_HALF_34 1u

/* The input clock of one half of one Timer64P, as an exact unreduced
 * fraction: *numerator Hz over *denominator, given AUXCLK in Hz from
 * cdj_c6747_pll_auxclk_hz().  AUXCLK is the timer's internal clock source:
 * SPRUH91D Table 6-2 printed page 104 (PDF page 104) and Table 7-1 printed
 * page 118 put "Timers" on AUXCLK, and 28.1.5.2.1 printed page 1229 says
 * the internal clock source "is generated by the PLL controller".  The PSC
 * does not appear in this path at all: Tables 8-1 and 8-2 printed pages 140
 * and 141 assign no LPSC to either Timer64P, and 8.2 printed page 140 says
 * such modules "do not have their module reset/clocks controlled by the PSC
 * module".
 * False wherever the manuals fix no rate; the outputs are then untouched.
 * This is a rate, not a run/stop condition: TGCR's TIMnRS resets, TCR's
 * ENAMODEn and TCR's TIEN12 external gate (printed pages 1253 and 1254) all
 * decide whether the counter advances, and none of them change this rate.
 * Nothing in this file counts - deliberately. */
bool cdj_c6747_timer_input_hz(const CdjC6747Timer *s, uint32_t auxclk_hz,
                              unsigned half, uint64_t *numerator,
                              uint32_t *denominator);

/* One output of one Timer64P, as a bit position in the cdj_c6747_timers_tick()
 * result.  Ten per timer: the two period interrupts and the eight CMPn
 * compare interrupts of Table 28-25 (printed page 1259). */
#define CDJ_C6747_TIMER_OUTPUTS 10u
#define CDJ_C6747_TIMER_OUT_TINT12 0u
#define CDJ_C6747_TIMER_OUT_TINT34 1u
#define CDJ_C6747_TIMER_OUT_CMP0 2u

/* Advance every Timer64P by one timer input clock period and return the set of
 * outputs that asserted, as bit i * CDJ_C6747_TIMER_OUTPUTS + output.
 *
 * WHAT ONE CALL MEANS IN TIME: nothing.  The boards call this from the CPU's
 * cycle_tick (cdj_c674x.h), so one input clock period is declared equal to one
 * modelled VLIW issue.  cpu->cycles is an issue count with no stall, memory
 * latency or cache model and no TI page relates it to Hz, so the step-to-tick
 * ratio is an approximation of nothing measurable - it is declared in both
 * provenance artifacts (tools/cdj_dsp/replay.py and tools/cdj_main/nxs_vm.py).
 * No test pins the ratio as a rate, but one test does bound it from one side:
 * tests/test_dsp_replay.py::test_timer64p_period_interrupt_reaches_the_cpu_in_replay
 * runs 4000 steps with PRD12 = 0x20 and asserts the period interrupt arrived,
 * which is a LIVENESS bound - measured to tolerate roughly 370x coarsening,
 * with no upper bound at all, since IFR is sticky and a faster counter cannot
 * fail it.  So making the tick much coarser turns that test red by design, not
 * by a timer bug.  It is NOT AUXCLK and NOT
 * cdj_c6747_timer_input_hz(); those answer the rate question, this one only
 * makes the counter advance monotonically so that period matches, reloads,
 * status bits and interrupts happen in the documented ORDER.
 *
 * Counting refuses, rather than guessing, wherever the input clock is a board
 * fact: TCR's CLKSRC12 external clock and TIEN12 external gate both depend on
 * the TM64P_IN12 pin (printed page 1253), whose level no manual page fixes.
 * 64-bit watchdog mode (TIMMODE = 2h) does not count at all, because a timeout
 * "resets the entire processor" (28.1.6.1, printed page 1240) and there is no
 * device-level reset here to drive. */
uint32_t cdj_c6747_timers_tick(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT]);

/* The SPRUH91D Table 2-1 DSP-interrupt-map event number one tick-result bit
 * raises, or 0 for a bit that is not an output (events 0..3 are the INTC's own
 * event-combiner outputs and are never a device event). */
unsigned cdj_c6747_timer_event(unsigned bit);

void cdj_c6747_timers_reset(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT]);
bool cdj_c6747_timers_read(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT],
                           uint32_t address, uint32_t *value);
/* Check phase is side-effect free. Reserved offsets, writes to REVID and
 * non-word accesses remain unmapped so validation runs fail closed. */
bool cdj_c6747_timers_write(CdjC6747Timer timers[CDJ_C6747_TIMER_COUNT],
                            uint32_t address, uint64_t value, unsigned size,
                            bool commit);

#endif
